language: php

php:
  - 5.3

branches:
  only:
    - master

before_script:
  - pear install DB
  - sh -c "psql -c \"CREATE USER ezpdo WITH PASSWORD 'pdoiseasy';\" -U postgres; fi"
  - sh -c "psql -c \"CREATE DATABASE ezpdo;\" -U postgres; fi"
  - sh -c "psql -c \"GRANT ALL PRIVILEGES ON DATABASE ezpdo TO ezpdo;\" -U postgres; fi"
  - sh -c "mysql -uroot -e \"CREATE USER 'ezpdo'@'localhost' IDENTIFIED BY 'pdoiseasy'; CREATE DATABASE IF NOT EXISTS ezpdo; GRANT ALL PRIVILEGES ON *.* TO 'ezpdo'@'localhost' WITH GRANT OPTION;\"; fi"

script: php tests/runtests.php
